<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Importation-of-necessary-libraries" data-toc-modified-id="Importation-of-necessary-libraries-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Importation of necessary libraries</a></span></li><li><span><a href="#Automatic-extraction-of-data-from-CSV-files" data-toc-modified-id="Automatic-extraction-of-data-from-CSV-files-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Automatic extraction of data from CSV files</a></span></li><li><span><a href="#Combination-of-all-the-necessary-data" data-toc-modified-id="Combination-of-all-the-necessary-data-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Combination of all the necessary data</a></span></li></ul></div>

# Importation of necessary libraries

In [1]:
import pandas as pd

import itertools

import numpy as np

# Automatic extraction of data from CSV files

In [2]:
df_Wall_Investment = pd.read_csv('../Input_Data_CSV/Wall_Investment.csv',
                                 sep=';',
                                 index_col=None,
                                 header=0)

df_Window_Investment = pd.read_csv('../Input_Data_CSV/Window_Investment.csv',
                                   sep=';',
                                   index_col=None,
                                   header=0)

df_Roof_Investment = pd.read_csv('../Input_Data_CSV/Roof_Investment.csv',
                                 sep=';',
                                 index_col=None,
                                 header=0)

df_Floor_Investment = pd.read_csv('../Input_Data_CSV/Floor_Investment.csv',
                                  sep=';',
                                  index_col=None,
                                  header=0)

df_Housing_Characteristics = pd.read_csv(
    '../Input_Data_CSV/Housing_Characteristics.csv',
    sep=';',
    index_col=None,
    header=0)

df_Climate_Zone = pd.read_csv('../Input_Data_CSV/Climate_Zone.csv',
                              sep=';',
                              index_col=None,
                              header=0)

df_Heating_System = pd.read_csv('../Input_Data_CSV/Heating_System.csv',
                                sep=';',
                                index_col=None,
                                header=0)

df_Headcount = pd.read_csv('../Input_Data_CSV/Headcount.csv',
                           sep=';',
                           index_col=None,
                           header=0)

df_Economic_Hypothesis = pd.read_csv(
    '../Input_Data_CSV/Economic_Hypothesis.csv',
    sep=';',
    index_col=None,
    header=0)

# Combination of all the necessary data

In [3]:
class All_Types:
    def __init__(self, *args):
        self.df_1 = df_Climate_Zone
        self.df_2 = df_Housing_Characteristics
        self.df_3 = df_Headcount
        self.df_4 = df_Heating_System
        self.df_5 = df_Economic_Hypothesis
        self.df_6 = df_Wall_Investment
        self.df_7 = df_Window_Investment
        self.df_8 = df_Roof_Investment
        self.df_9 = df_Floor_Investment

In [4]:
class Type_CID(All_Types):
    def init(self, *args):
        super().init(*args)

    def List_Itertools(self):
        self.list_itertools = []
        list_dwelling_type = ['CID']
        list_climate_type = self.df_1.iloc[:, 0].tolist()
        list_construction_period = self.df_2.iloc[:21, 1].tolist()[::3]
        list_size_factor = self.df_2.iloc[:3, 2].tolist()
        list_heating_system = [
            'ER', 'GB', 'CGB', 'OB', 'COB', 'EHP2', 'WB', 'WPB', 'EHP'
        ]
        list_initial_age = self.df_3.iloc[:20, 5].tolist()
        self.list_itertools.append(list_dwelling_type)
        self.list_itertools.append(list_climate_type)
        self.list_itertools.append(list_construction_period)
        self.list_itertools.append(list_size_factor)
        self.list_itertools.append(list_heating_system)
        self.list_itertools.append(list_initial_age)
        return self.list_itertools

    def List_to_DF(self):
        self.List_Itertools()
        itertools_product = list(itertools.product(*self.list_itertools))
        self.df = pd.DataFrame(itertools_product,
                               columns=[
                                   'Dwelling Type', 'Climate Type',
                                   'Construction Period', 'Size Factor',
                                   'Heating System', 'Initial Age'
                               ])
        return self.df

    def DFs_Merge(self):
        self.List_to_DF()
        self.df = self.df.merge(self.df_1, how='left', on=['Climate Type'])
        self.df = self.df.merge(self.df_2.iloc[:21, 1:9],
                                how='left',
                                on=['Construction Period', 'Size Factor'])
        self.df = self.df.merge(self.df_4.iloc[:9, :],
                                how='left',
                                on=['Heating System'])
        return self.df

    def Cols_Add(self):
        self.DFs_Merge()
        self.df[self.df_5.columns[0]] = self.df_5.iloc[0, 0]
        self.df[self.df_5.columns[1]] = self.df_5.iloc[0, 1]
        self.df[self.df_5.columns[2]] = self.df_5.iloc[0, 2]
        self.df[self.df_5.columns[3]] = self.df_5.iloc[0, 3]
        return self.df

    def Complete_DF_without_U(self):
        self.Cols_Add()
        self.df = pd.concat([self.df, self.df_3.iloc[0:11340, 6]],
                            axis=1,
                            join='outer')
        return self.df

    def Cols_Reorder(self):
        self.Complete_DF_without_U()
        cols = self.df.columns.tolist()
        reordered_cols = cols[:2] + cols[6:7] + cols[2:4] + cols[7:13] + \
        cols[4:5] + cols[13:27] + cols[5:6] + cols[27:28]
        self.df = self.df[reordered_cols]
        return self.df

    def DF_with_U_Factors(self):
        self.Cols_of_Initial_U()
        self.df = self.df.merge(
            self.df_2.loc[:20, ['Construction Period', 'Size Factor', 'Um0']],
            how='left',
            on=['Construction Period', 'Size Factor'])
        for m in range(18):
            self.df['Um' + str(m + 1)] = self.df_6.iloc[m, 2]
        self.df = self.df.merge(
            self.df_2.loc[:20, ['Construction Period', 'Size Factor', 'Uw0']],
            how='left',
            on=['Construction Period', 'Size Factor'])
        for w in range(3):
            self.df['Uw' + str(w + 1)] = self.df_7.iloc[w, 2]
        self.df = self.df.merge(
            self.df_2.loc[:20, ['Construction Period', 'Size Factor', 'Ur0']],
            how='left',
            on=['Construction Period', 'Size Factor'])
        for r in range(3):
            self.df['Ur' + str(r + 1)] = self.df_8.iloc[r, 2]
        self.df = self.df.merge(
            self.df_2.loc[:20, ['Construction Period', 'Size Factor', 'Uf0']],
            how='left',
            on=['Construction Period', 'Size Factor'])
        for f in range(5):
            self.df['Uf' + str(f + 1)] = self.df_9.iloc[f, 2]
        return self.df

    def DF_with_U_Prices(self):
        self.Cols_of_Initial_U()
        self.df['Um0'] = 0
        for m in range(18):
            self.df['Um' + str(m + 1)] = self.df_6.iloc[m, 3]

        self.df['Uw0'] = 0
        for w in range(3):
            self.df['Uw' + str(w + 1)] = self.df_7.iloc[w, 3]

        self.df['Ur0'] = 0
        for r in range(3):
            self.df['Ur' + str(r + 1)] = self.df_8.iloc[r, 3]

        self.df['Uf0'] = 0
        for f in range(5):
            self.df['Uf' + str(f + 1)] = self.df_9.iloc[f, 3]
        return self.df

In [5]:
class First_Year_CID(Type_CID):
    def init(self, *args):
        super().init(*args)

    def Cols_of_Initial_U(self):
        self.Cols_Reorder()
        self.df['Initial Um'] = 0
        self.df['Initial Uw'] = 0
        self.df['Initial Ur'] = 0
        self.df['Initial Uf'] = 0
        return self.df

In [6]:
First_Year_CID = First_Year_CID()
df_with_U_Factors = First_Year_CID.DF_with_U_Factors()
df_with_U_Prices = First_Year_CID.DF_with_U_Prices()

In [7]:
df_with_U_Factors.shape == df_with_U_Prices.shape

True

In [8]:
df_with_U_Factors.columns == df_with_U_Prices.columns

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [9]:
df_with_U_Factors.head() == df_with_U_Prices.head()

,Dwelling Type,Climate Type,Degrees of Reference,Construction Period,Size Factor,Surface,Ceiling Height,Share of Windows,Dwelling per Floor,Floors,...,Ur0,Ur1,Ur2,Ur3,Uf0,Uf1,Uf2,Uf3,Uf4,Uf5
0,True,True,True,True,True,True,True,True,True,True,...,False,False,False,False,False,False,False,False,False,False
1,True,True,True,True,True,True,True,True,True,True,...,False,False,False,False,False,False,False,False,False,False
2,True,True,True,True,True,True,True,True,True,True,...,False,False,False,False,False,False,False,False,False,False
3,True,True,True,True,True,True,True,True,True,True,...,False,False,False,False,False,False,False,False,False,False
4,True,True,True,True,True,True,True,True,True,True,...,False,False,False,False,False,False,False,False,False,False

In [10]:
df_with_U_Factors.to_csv('../Output_Data_CSV/1_DataFrame_with_U_Factors.csv',
                         sep=';',
                         index=None,
                         header=True,
                         encoding='utf-8')

In [11]:
df_with_U_Prices.to_csv('../Output_Data_CSV/2_DataFrame_with_U_Prices.csv',
                        sep=';',
                        index=None,
                        header=True,
                        encoding='utf-8')

In [12]:
class Calculable_Cols:
    def __init__(self, df):
        self.df = df

In [13]:
class Cols_for_Collective_Dwelling(Calculable_Cols):
    def init(self, df):
        super().init(df)

    def Cols_Rename(self):
        self.df.rename(columns={
            name: name.replace(' ', '_')
            for name in self.df.columns if name.count(' ') > 0
        },
                       inplace=1)
        return self.df

    def Col_Surface_m(self):
        self.Cols_Rename()
        A = np.subtract(1, self.df.Share_of_Windows)
        B = np.sqrt(np.multiply(self.df.Surface, self.df.Dwelling_per_Floor))
        C = np.add(self.df.Floors, 1)
        D = np.multiply(np.multiply(A, B), 4)
        E = np.multiply(self.df.Ceiling_Height, C)
        self.df['Surface_m'] = np.multiply(D, E)
        return self.df

    def Col_Surface_w(self):
        self.Cols_Rename()
        A = np.sqrt(np.multiply(self.df.Surface, self.df.Dwelling_per_Floor))
        B = np.add(self.df.Floors, 1)
        C = np.multiply(np.multiply(self.df.Share_of_Windows, A), 4)
        D = np.multiply(self.df.Ceiling_Height, B)
        self.df['Surface_w'] = np.multiply(C, D)
        return self.df

    def Col_Surface_r(self):
        self.Cols_Rename()
        self.df['Surface_r'] = np.multiply(self.df.Surface,
                                           self.df.Dwelling_per_Floor)
        return self.df

    def Weighted_U_Factors(self):
        self.Col_Surface_m()
        self.Col_Surface_w()
        self.Col_Surface_r()
        self.df.loc[:, 'Um0':'Um18'] = self.df.loc[:, 'Um0':'Um18'].apply(
            lambda x: np.multiply(x, self.df.Surface_m))
        self.df.loc[:, 'Uw0':'Uw3'] = self.df.loc[:, 'Uw0':'Uw3'].apply(
            lambda x: np.multiply(x, self.df.Surface_w))
        self.df.loc[:, 'Ur0':'Ur3'] = self.df.loc[:, 'Ur0':'Ur3'].apply(
            lambda x: np.multiply(x, self.df.Surface_r))
        self.df.loc[:, 'Uf0':'Uf5'] = self.df.loc[:, 'Uf0':'Uf5'].apply(
            lambda x: np.multiply(x, self.df.Surface_r))
        return self.df

    #######
    def Col_Dwelling_total(self):
        self.Cols_Rename()
        A = np.add(self.df.Floors, 1)
        self.df['Dwelling_total'] = np.multiply(self.df.Dwelling_per_Floor,\
                                                A)
        return self.df

In [14]:
class Calculable_DFs:
    def __init__(self, df):
        self.df = df

In [15]:
class DFs_for_Collective_Dwelling(Calculable_DFs):
    def init(self, df):
        super().init(df)

    def Cols_to_Swith_Add(self):
        cols_list = []
        for m in range(19):
            for w in range(4):
                for r in range(4):
                    for f in range(6):
                        for to_swith in [
                                'ER', 'GB', 'CGB', 'OB', 'COB', 'EHP2', 'WB',
                                'WPB', 'EHP'
                        ]:
                            col_name = str(m) + '_' + str(w) + '_' + str(
                                r) + '_' + str(f) + '_' + to_swith
                            cols_list.append(col_name)
        self.df = pd.concat(
            [self.df,
             pd.DataFrame(0, index=self.df.index, columns=cols_list)],
            axis=1)
        return self.df

    def Combine_Weighted_U_Factors(self):
        self.Cols_to_Swith_Add()
        selected_cols = self.df.columns.tolist()[-16416:]
        self.df[selected_cols] = self.df[selected_cols].apply(lambda x: np.add(
            np.add(self.df['Um' + x.name.split('_')[0]], self.df[
                'Uw' + x.name.split('_')[1]]),
            np.add(self.df['Ur' + x.name.split('_')[2]], self.df[
                'Uf' + x.name.split('_')[3]])))
        return self.df

In [16]:
a = Cols_for_Collective_Dwelling(df_with_U_Factors)
b = a.Weighted_U_Factors()
c = DFs_for_Collective_Dwelling(b)

In [17]:
d = c.Combine_Weighted_U_Factors()

In [18]:
d

      Dwelling_Type Climate_Type  Degrees_of_Reference Construction_Period  \
0               CID           H1                 59488               <1948
1               CID           H1                 59488               <1948
2               CID           H1                 59488               <1948
3               CID           H1                 59488               <1948
4               CID           H1                 59488               <1948
5               CID           H1                 59488               <1948
6               CID           H1                 59488               <1948
7               CID           H1                 59488               <1948
8               CID           H1                 59488               <1948
9               CID           H1                 59488               <1948
10              CID           H1                 59488               <1948
11              CID           H1                 59488               <1948
12              CID           H1                 59488               <1948
13              CID           H1                 59488               <1948
14              CID           H1                 59488               <1948
15              CID           H1                 59488               <1948
16              CID           H1                 59488               <1948
17              CID           H1                 59488               <1948
18              CID           H1                 59488               <1948
19              CID           H1                 59488               <1948
20              CID           H1                 59488               <1948
21              CID           H1                 59488               <1948
22              CID           H1                 59488               <1948
23              CID           H1                 59488               <1948
24              CID           H1                 59488               <1948
25              CID           H1                 59488               <1948
26              CID           H1                 59488               <1948
27              CID           H1                 59488               <1948
28              CID           H1                 59488               <1948
29              CID           H1                 59488               <1948
...             ...          ...                   ...                 ...
11310           CID           H3                 34281           2006-2013
11311           CID           H3                 34281           2006-2013
11312           CID           H3                 34281           2006-2013
11313           CID           H3                 34281           2006-2013
11314           CID           H3                 34281           2006-2013
11315           CID           H3                 34281           2006-2013
11316           CID           H3                 34281           2006-2013
11317           CID           H3                 34281           2006-2013
11318           CID           H3                 34281           2006-2013
11319           CID           H3                 34281           2006-2013
11320           CID           H3                 34281           2006-2013
11321           CID           H3                 34281           2006-2013
11322           CID           H3                 34281           2006-2013
11323           CID           H3                 34281           2006-2013
11324           CID           H3                 34281           2006-2013
11325           CID           H3                 34281           2006-2013
11326           CID           H3                 34281           2006-2013
11327           CID           H3                 34281           2006-2013
11328           CID           H3                 34281           2006-2013
11329           CID           H3                 34281           2006-2013
11330           CID           H3                 34281           2006-2013
11331           CID           H3                 34281           2006-2013
11332           CID           H3                 34281           2006-2013
11333           CID           H3                 34281           2006-2013
11334           CID           H3                 34281           2006-2013
11335           CID           H3                 34281           2006-2013
11336           CID           H3                 34281           2006-2013
11337           CID           H3                 34281           2006-2013
11338           CID           H3                 34281           2006-2013
11339           CID           H3                 34281           2006-2013

      Size_Factor  Surface  Ceiling_Height  Share_of_Windows  \
0          Middle     60.5            2.98              0.28
1          Middle     60.5            2.98              0.28
2          Middle     60.5            2.98              0.28
3          Middle     60.5            2.98              0.28
4          Middle     60.5            2.98              0.28
5          Middle     60.5            2.98              0.28
6          Middle     60.5            2.98              0.28
7          Middle     60.5            2.98              0.28
8          Middle     60.5            2.98              0.28
9          Middle     60.5            2.98              0.28
10         Middle     60.5            2.98              0.28
11         Middle     60.5            2.98              0.28
12         Middle     60.5            2.98              0.28
13         Middle     60.5            2.98              0.28
14         Middle     60.5            2.98              0.28
15         Middle     60.5            2.98              0.28
16         Middle     60.5            2.98              0.28
17         Middle     60.5            2.98              0.28
18         Middle     60.5            2.98              0.28
19         Middle     60.5            2.98              0.28
20         Middle     60.5            2.98              0.28
21         Middle     60.5            2.98              0.28
22         Middle     60.5            2.98              0.28
23         Middle     60.5            2.98              0.28
24         Middle     60.5            2.98              0.28
25         Middle     60.5            2.98              0.28
26         Middle     60.5            2.98              0.28
27         Middle     60.5            2.98              0.28
28         Middle     60.5            2.98              0.28
29         Middle     60.5            2.98              0.28
...           ...      ...             ...               ...
11310       Large     94.0            2.60              0.30
11311       Large     94.0            2.60              0.30
11312       Large     94.0            2.60              0.30
11313       Large     94.0            2.60              0.30
11314       Large     94.0            2.60              0.30
11315       Large     94.0            2.60              0.30
11316       Large     94.0            2.60              0.30
11317       Large     94.0            2.60              0.30
11318       Large     94.0            2.60              0.30
11319       Large     94.0            2.60              0.30
11320       Large     94.0            2.60              0.30
11321       Large     94.0            2.60              0.30
11322       Large     94.0            2.60              0.30
11323       Large     94.0            2.60              0.30
11324       Large     94.0            2.60              0.30
11325       Large     94.0            2.60              0.30
11326       Large     94.0            2.60              0.30
11327       Large     94.0            2.60              0.30
11328       Large     94.0            2.60              0.30
11329       Large     94.0            2.60              0.30
11330       Large     94.0            2.60              0.30
11331       Large     94.0            2.60              0.30
11332       Large     94.0            2.60              0.30
11333       Large     94.0            2.60              0.30
11334       Large     94.0            2.60              0.30
11335       Large     94.0            2.60              0.30
11336       Large     94.0            2.60              0.30
11337       Large     94.0            2.60              0.30
11338       Large     94.0            2.60              0.30
11339       Large     94.0            2.60              0.30

       Dwelling_per_Floor  Floors  ...  18_3_3_4_EHP 18_3_3_5_ER  18_3_3_5_GB  \
0                       2       5  ...    463.641904  458.801904   458.801904
1                       2       5  ...    463.641904  458.801904   458.801904
2                       2       5  ...    463.641904  458.801904   458.801904
3                       2       5  ...    463.641904  458.801904   458.801904
4                       2       5  ...    463.641904  458.801904   458.801904
5                       2       5  ...    463.641904  458.801904   458.801904
6                       2       5  ...    463.641904  458.801904   458.801904
7                       2       5  ...    463.641904  458.801904   458.801904
8                       2       5  ...    463.641904  458.801904   458.801904
9                       2       5  ...    463.641904  458.801904   458.801904
10                      2       5  ...    463.641904  458.801904   458.801904
11                      2       5  ...    463.641904  458.801904   458.801904
12                      2       5  ...    463.641904  458.801904   458.801904
13                      2       5  ...    463.641904  458.80

In [19]:
np.add(d.iloc[:, -1:], d.iloc[:, -3:-2])

       18_3_3_5_EHP
0        917.603808
1        917.603808
2        917.603808
3        917.603808
4        917.603808
5        917.603808
6        917.603808
7        917.603808
8        917.603808
9        917.603808
10       917.603808
11       917.603808
12       917.603808
13       917.603808
14       917.603808
15       917.603808
16       917.603808
17       917.603808
18       917.603808
19       917.603808
20       917.603808
21       917.603808
22       917.603808
23       917.603808
24       917.603808
25       917.603808
26       917.603808
27       917.603808
28       917.603808
29       917.603808
...             ...
11310   1228.670708
11311   1228.670708
11312   1228.670708
11313   1228.670708
11314   1228.670708
11315   1228.670708
11316   1228.670708
11317   1228.670708
11318   1228.670708
11319   1228.670708
11320   1228.670708
11321   1228.670708
11322   1228.670708
11323   1228.670708
11324   1228.670708
11325   1228.670708
11326   1228.670708
11327   1228.670708
11328   1228.670708
11329   1228.670708
11330   1228.670708
11331   1228.670708
11332   1228.670708
11333   1228.670708
11334   1228.670708
11335   1228.670708
11336   1228.670708
11337   1228.670708
11338   1228.670708
11339   1228.670708

[11340 rows x 1 columns]

In [20]:
d.iloc[:, -200:]

       18_3_0_1_WPB  18_3_0_1_EHP  18_3_0_2_ER  18_3_0_2_GB  18_3_0_2_CGB  \
0                 0             0            0            0             0
1                 0             0            0            0             0
2                 0             0            0            0             0
3                 0             0            0            0             0
4                 0             0            0            0             0
5                 0             0            0            0             0
6                 0             0            0            0             0
7                 0             0            0            0             0
8                 0             0            0            0             0
9                 0             0            0            0             0
10                0             0            0            0             0
11                0             0            0            0             0
12                0             0            0            0             0
13                0             0            0            0             0
14                0             0            0            0             0
15                0             0            0            0             0
16                0             0            0            0             0
17                0             0            0            0             0
18                0             0            0            0             0
19                0             0            0            0             0
20                0             0            0            0             0
21                0             0            0            0             0
22                0             0            0            0             0
23                0             0            0            0             0
24                0             0            0            0             0
25                0             0            0            0             0
26                0             0            0            0             0
27                0             0            0            0             0
28                0             0            0            0             0
29                0             0            0            0             0
...             ...           ...          ...          ...           ...
11310             0             0            0            0             0
11311             0             0            0            0             0
11312             0             0            0            0             0
11313             0             0            0            0             0
11314             0             0            0            0             0
11315             0             0            0            0             0
11316             0             0            0            0             0
11317             0             0            0            0             0
11318             0             0            0            0             0
11319             0             0            0            0             0
11320             0             0            0            0             0
11321             0             0            0            0             0
11322             0             0            0            0             0
11323             0             0            0            0             0
11324             0             0            0            0             0
11325             0             0            0            0             0
11326             0             0            0            0             0
11327             0             0            0            0             0
11328             0             0            0            0             0
11329             0             0            0            0             0
11330             0             0            0            0             0
11331             0             0            0            0             0
11332             0             0            0            0             0
11333             0             0            0            0             0
11334             0             0            0            0             0
11335             0             0            0            0             0
11336             0             0            0            0             0
11337             0             0            0            0             0
11338             0             0            0            0             0
11339             0             0            0            0             0

       18_3_0_2_OB  18_3_0_2_COB  18_3_0_2_EHP2  18_3_0_2_WB  18_3_0_2_WPB  \
0                0             0              0            0             0
1                0             0              0            0             0
2                0             0              0            0             0
3                0             0              0            0             0
4                0             0              0            0             0
5                0             0              0            0             0
6                0             0              0            0             0
7                0             0              0            0             0
8                0             0              0            0             0
9                0             0              0            0             0
10               0             0              0            0             0
11               0             0              0            0             0
12               0             0              0            0             0
13               0             0              0            0             0
14               0             0              0            0             0
15               0             0              0            0             0
16               0             0              0            0             0
17               0             0              0            0             0
18               0             0              0            0             0
19               0             0              0            0             0
20               0             0              0            0             0
21               0             0              0            0             0
22               0             0              0            0             0
23               0             0              0            0             0
24               0             0              0            0             0
25               0             0              0            0             0
26               0             0              0            0             0
27               0             0              0            0             0
28               0             0              0            0             0
29               0             0              0            0             0
...            ...           ...            ...          ...           ...
11310            0             0              0            0             0
11311            0             0              0            0             0
11312            0             0              0            0             0
11313            0             0              0            0             0
11314            0             0              0            0             0
11315            0             0              0            0             0
11316            0             0              0            0             0
11317            0             0              0            0             0
11318            0             0              0            0             0
11319            0             0              0            0             0
11320            0             0              0            0             0
11321            0             0              0            0             0
11322            0             0              0            0             0
11323            0             0              0            0             0
11324            0             0              0            0             0
11325            0             0              0            0             0
11326            0             0              0            0             0
11327            0             0              0            0             0
11328            0             0              0            0             0
11329            0             0              0            0             0
11330            0             0              0            0             0
11331            0             0              0            0             0
11332            0             0              0            0             0
11333            0             0              0            0             0
11334            0             0              0            0             0
11335            0             0              0            0             0
11336            0             0              0            0             0
11337            0             0              0            0             0
11338            0             0              0            0             0
11339            0             0              0            0             0

       ...  18_3_3_4_EHP  18_3_3_5_ER  18_3_3_5_GB  18_3_3_5_CGB  18_3_3_5_OB  \
0      ...    463.641904   458.801904   458.801904    458.801904   458.801904
1      ...    463.641904   458.801904   458.801904    458.801904   458.801904
2      ...    463.641904   458.801904   458.801904    458.801904   458.801904
3      ...    463.641904   458.801904   458.801904    458.801904

In [21]:
a = d.columns.tolist()[-16416:]
d[a]

       0_0_0_0_ER  0_0_0_0_GB  0_0_0_0_CGB  0_0_0_0_OB  0_0_0_0_COB  \
0               0           0            0           0            0
1               0           0            0           0            0
2               0           0            0           0            0
3               0           0            0           0            0
4               0           0            0           0            0
5               0           0            0           0            0
6               0           0            0           0            0
7               0           0            0           0            0
8               0           0            0           0            0
9               0           0            0           0            0
10              0           0            0           0            0
11              0           0            0           0            0
12              0           0            0           0            0
13              0           0            0           0            0
14              0           0            0           0            0
15              0           0            0           0            0
16              0           0            0           0            0
17              0           0            0           0            0
18              0           0            0           0            0
19              0           0            0           0            0
20              0           0            0           0            0
21              0           0            0           0            0
22              0           0            0           0            0
23              0           0            0           0            0
24              0           0            0           0            0
25              0           0            0           0            0
26              0           0            0           0            0
27              0           0            0           0            0
28              0           0            0           0            0
29              0           0            0           0            0
...           ...         ...          ...         ...          ...
11310           0           0            0           0            0
11311           0           0            0           0            0
11312           0           0            0           0            0
11313           0           0            0           0            0
11314           0           0            0           0            0
11315           0           0            0           0            0
11316           0           0            0           0            0
11317           0           0            0           0            0
11318           0           0            0           0            0
11319           0           0            0           0            0
11320           0           0            0           0            0
11321           0           0            0           0            0
11322           0           0            0           0            0
11323           0           0            0           0            0
11324           0           0            0           0            0
11325           0           0            0           0            0
11326           0           0            0           0            0
11327           0           0            0           0            0
11328           0           0            0           0            0
11329           0           0            0           0            0
11330           0           0            0           0            0
11331           0           0            0           0            0
11332           0           0            0           0            0
11333           0           0            0           0            0
11334           0           0            0           0            0
11335           0           0            0           0            0
11336           0           0            0           0            0
11337           0           0            0           0            0
11338           0           0            0           0            0
11339           0           0            0           0            0

       0_0_0_0_EHP2  0_0_0_0_WB  0_0_0_0_WPB  0_0_0_0_EHP  0_0_0_1_ER  ...  \
0                 0           0            0            0           0  ...
1                 0           0            0            0           0  ...
2                 0           0            0            0           0  ...
3                 0           0            0            0           0  ...
4                 0           0            0            0           0  ...
5                 0           0            0            0           0  ...
6                 0           0            0            0           0  ...
7                 0           0            0            0           0  ...
8                 0           0            0            0           0  ...
9                 0           0            0            0           0  ...
10                0           0            0            0           0  ...
11                0           0            0            0           0  ...
12                0           0            0            0           0  ...
13                0           0            0            0           0  ...
14                0           0            0            0           0  ...
15                0           0            0            0           0  ...
16                0           0            0            0           0  ...
17                0           0            0            0           0  ...
18                0           0            0            0           0  ...
19                0           0            0            0           0  ...
20                0           0            0            0           0  ...
21                0           0            0            0           0  ...
22                0           0            0            0           0  ...
23                0           0            0            0           0  ...
24                0           0            0            0           0  ...
25                0           0            0            0           0  ...
26                0           0            0            0           0  ...
27                0           0            0            0           0  ...
28                0           0            0            0           0  ...
29                0           0            0            0           0  ...
...             ...         ...          ...          ...         ...  ...
11310             0           0            0            0           0  ...
11311             0           0            0            0           0  ...
11312             0           0            0            0           0  ...
11313             0           0            0            0           0  ...
11314             0           0            0            0           0  ...
11315             0           0            0            0           0  ...
11316             0           0            0            0           0  ...
11317             0           0            0            0           0  ...
11318             0           0            0            0           0  ...
11319             0           0            0            0           0  ...
11320             0           0            0            0           0  ...
11321             0           0            0            0           0  ...
11322             0           0            0            0           0  ...
11323             0           0            0            0           0  ...
11324             0           0            0            0           0  ...
11325             0           0            0            0           0  ...
11326             0           0            0            0           0  ...
11327             0           0            0            0           0  ...
11328             0           0            0            0           0  ...
11329             0           0            0            0           0  ...
11330             0           0            0            0           0  ...
11331             0           0            0            0           0  ...
11332             0           0            0            0           0  ...
11333             0           0            0            0           0  ...
11334             0           0            0            0           0  ...
11335             0           0            0            0           0  ...
11336             0           0            0            0           0  ...
11337             0           0            0            0           0  ...
11338             0           0            0            0           0  ...
11339             0           0            0            0           0  ...

       18_3_3_4_EHP  18_3_3_5_ER  18_3_3_5_GB  18_3_3_5_CGB  18_3_3_5_OB  \
0        463.641904   458.801904   458.801904    458.801904   458.801904
1        463.641904   458.801904   458.801904    458.801904   458.801904
2        463.641904   458.801904   458.801904    458.801904   458.801904
3        463.641904   458.801904   458.801904    458.801904   458.801904
4        463.641904   458.801904   458.801904    458.801904   458.801904
5        463.641904   458.801904   458.801904    458.801904   458.801904
6        463.641904   458.801904   458.801904    458.801904   458.801904
7        463.641904   458.801904   458.801904    458.801904   458.801904
8        463.641904   458.801904   458.801904    458.801904   458.801904

In [22]:
%timeit d.iloc[:, -16416 :]

887 ms ± 159 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [23]:
%timeit d.iloc[:, 69 : ]

860 ms ± 128 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [24]:
'Um' + '0_1_2_3_ER'.split('_')[0]

'Um0'

In [25]:
%%timeit
A = np.subtract(1, df_with_U_Factors.Floors)
B = np.add(1, df_with_U_Factors.Floors)
np.add(A, B)
del A, B

394 µs ± 77.2 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

In [ ]:
%%timeit
np.add(np.subtract(1, df_with_U_Factors.Floors),
       np.add(1, df_with_U_Factors.Floors))

463 µs ± 165 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

In [ ]:
cols = df_CID.Complete_DF_without_U().columns.tolist()

reordered_cols = cols[:2] + cols[6:7] + cols[2:4] + cols[7:13] + cols[
    4:5] + cols[13:27] + cols[5:6] + cols[27:28]

reordered_cols

In [ ]:
cols = df_with_U_Factors.columns
cols = cols.map(lambda x: x.replace(' ', '_')
                if isinstance(x, (str, unicode)) else x)
df_with_U_Factors.columns = cols

In [ ]:
df_with_U_Factors.loc[df_with_U_Factors.shape[0]] = 1

In [ ]:
df_with_U_Factors.shape

In [ ]:
name = '10_2_2_1_ER'
name = name.split('_')
name[0] + name[1]

In [ ]:
df_with_U_Factors.rename(columns={
    k: k.replace(' ', '_')
    for k in df_with_U_Factors.columns if k.count(' ') > 0
},
                         inplace=1)

df_with_U_Factors

In [ ]:
df_with_U_Factors

#pd.options.mode.chained_assignment = None
import math